### ISSUE TITLE
cannot load http://localhost:8080

### ISSUE THREAD

**Issue by talley** [VahidN/DNTProfiler#4]
I updated my web.config file and lunched the demo web app.But when i go to http://localhost:8080 i got Unable to connect.

Thanks.
Talley

**Comment by VahidN** [comment]
You need to run the DNTProfiler application too. You can download it [from here](https://github.com/VahidN/DNTProfiler/releases). DNTProfiler application creates a server and then starts listening to the logs that are coming from your application.
